In [ ]:
import render_array as render



In [24]:
# CIRCLES BOY
import numpy as np
import math
# ILL FUCKING DO IT MYSELF:
# MAKE SQUARE ARRAY:
#(x,y) = 10,10
# how the fuck does this work
#fart = np.array([xv if c else yv for c, xv, yv in zip(c, x,y)])
f = np.arange(10000).reshape(100,100)
shitcircle = np.array([0xFFFFFFF if math.sqrt(x**x+y**y)<50 else 0 for x,y in zip(list(range(100)),list(range(100)))])
# FUCKING CUNT
print(shitcircle)

[268435455 268435455 268435455 268435455 268435455         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
         0         0         0         0         0         0         0
      

In [33]:
import numpy as np

#fucking insert something

full = np.full((10,10),0)
sub = np.arange(1,5).reshape(2,2)
start = x,y = 2,2
full[x:x+sub.shape[0],y:y+sub.shape[1]] = sub
print(full)
print(full.shape > sub.shape)


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 2 0 0 0 0 0 0]
 [0 0 3 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
True


In [29]:
import numpy as np

# Now for some checkies:

big = np.full((10,10),0)
small = np.full((2,2),2)
wide = np.full((2,15),5)
tall = np.full((15,2),7)


print('RESULT: HAVE TO COMPARE BOTH DIMENSIONS SEPARATELY')

big:(10, 10),small:(2, 2)
wide:(2, 15),tall:(15, 2)
big>small
True
small<big
False
big>wide
True
big>tall
False


In [110]:
# figure out this fucking ref/value shit:

# STEP 1:
import numpy as np

def overwrite(dest,source,loc):
    (y,x) = loc
    if (x < 0):
        print('x low')
        source = source[abs(x):,:]
        x = 0
    if (y < 0):
        print('y low')
        source = source[:,abs(y):]
        y = 0
    if ((source.shape[0]+x) > dest.shape[0]):
        print('x high')
        source = source[:dest.shape[0]-x,:]
    if ((source.shape[1]+y) > dest.shape[1]):
        print('y high')
        source = source[:,:dest.shape[1]-y]
    print(f'dest = ({dest.shape[0]},{dest.shape[1]}), source = ({source.shape[0]},{source.shape[1]})')
    dest[x:x+source.shape[0],y:y+source.shape[1]] = source

a = np.full((10,10),0)
b = np.full((5,5),1)
x,y = (-3,2)
print(b.shape)
b = b[abs(x):,:]
overwrite(a,b,(x,y))
print(a)


(5, 5)
y low
dest = (10,10), source = (2,2)
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]]


In [116]:
import timeit

In [121]:
def over(dest,source,loc):
    (x,y) = loc
    if (x < 0):
        source = source[abs(x):]
        x = 0
    if (y < 0):
        source = source[:,abs(y):]
        y = 0
    if (source.shape[0]+x > dest.shape[0]):
        source = source[:dest.shape[0]-x,:]
    if (source.shape[1]+y > dest.shape[1]):
        source = source[:,:(dest.shape[1]-y)]
    dest[x:x+source.shape[0],y:y+source.shape[1]] = source

a = np.full((10,10),0)
b = np.full((5,5),1)
c = np.full((11,11),2)



In [151]:
setup = '''
import numpy as np

a = np.full((10,10),0)
b = np.full((5,5),1)
c = np.full((11,11),2)

def over(dest,source,loc):
    (x,y) = loc
    if (x < 0):
        source = source[abs(x):]
        x = 0
    if (y < 0):
        source = source[:,abs(y):]
        y = 0
    if (source.shape[0]+x > dest.shape[0]):
        source = source[:dest.shape[0]-x,:]
    if (source.shape[1]+y > dest.shape[1]):
        source = source[:,:(dest.shape[1]-y)]
    dest[x:x+source.shape[0],y:y+source.shape[1]] = source
'''
code = '''
over(a,b,(1,1))
'''
timed = timeit.timeit(code,setup,number = 5600)
print(timed)
print(1/120)

0.008022399999390473
0.008333333333333333
