In [2]:
# Dissection pt1: how the fuck do arrays work?
import numpy

# getting random num gen:
grid = numpy.random.randint(0, 0xFFFFFF + 1, (3, 3), numpy.int32)

print(grid)
# okay so this just transforms every individual number in the array into 0
grid[:] = 0
print(grid)
print(type(grid))

[[ 5718225 12779660  8121428]
 [10767767 16034103  3198058]
 [ 5866457   365918  1548918]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


In [27]:

whatever = [[69,1,1],[1,69,1],[1,1,69]]
# regrid = numpy.ndarray(shape=(3,3),whatever)
yes = numpy.array(whatever)
print(yes[1:])


[[1 69 1]
 [1 1 69]]


C:\Users\derek\AppData\Local\Temp/ipykernel_7428/1774006166.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  yes = numpy.array(whatever)


In [2]:
# MASKING WITH NUMPY
import numpy
# standard python list if I need to compare
list1 = [[1,2,3],[4,5,6],[7,8,9]]

arr1 = numpy.random.randint(1,1000,(4,4))
# Makes 4x4 array w/rand ints:
print(arr1)
# Creates an array with same format as given array
arr2 = -(numpy.ones_like(arr1))
# Range 4 goes to 3
for i in range(0,4):
    arr2[i][i] = 69

# USING A MASK TO OVERWRITE ONE ARRAY WITH SELECTED PORTION OF ANOTHER
# Easy boolean if equals
mask = (arr2 != -1)
print(arr2)
print(mask)
newarr = numpy.copy(arr1)
newarr[mask] = arr2[mask]
print(newarr)

[[ 53 883 192 742]
 [837 698 922 801]
 [730 630  91 898]
 [271 781 469 519]]
[[69 -1 -1 -1]
 [-1 69 -1 -1]
 [-1 -1 69 -1]
 [-1 -1 -1 69]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ 69 883 192 742]
 [837  69 922 801]
 [730 630  69 898]
 [271 781 469  69]]


In [71]:
# How do I fucking blow this shit up

list1 = [[1,2,3],[4,5,6],[7,8,9]]
grid = numpy.array(list1)
dupe = (numpy.repeat(numpy.repeat(grid,2,axis=1),2,axis=0))
print(dupe)

[[1 1 2 2 3 3]
 [1 1 2 2 3 3]
 [4 4 5 5 6 6]
 [4 4 5 5 6 6]
 [7 7 8 8 9 9]
 [7 7 8 8 9 9]]


In [63]:
# what is this step doing???
# Base random color array gen for each pixel
# grid = numpy.random.randint(0, 10, (3,3))

# Just look at it with set one so can see actual behavior
list1 = [[1,2,3],[4,5,6],[7,8,9]]
grid = numpy.array(list1)
# Part 1 of quad-directional shifting:
shifted = []
# WHEN dx = dy, there is a DIAGONAL shift happening.
for dx in [-1, 1]:
    for dy in [-1, 1]:
        if (dx, dy) != (0, 0):
            shifted.append(numpy.roll(grid, (dx, dy), (0, 1)))
# Order of shifted: [-1,-1],[-1,0],[-1,1],[0,-1],etc
print(grid)
for x in shifted:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6 4]
 [8 9 7]
 [2 3 1]]
[[6 4 5]
 [9 7 8]
 [3 1 2]]
[[8 9 7]
 [2 3 1]
 [5 6 4]]
[[9 7 8]
 [3 1 2]
 [6 4 5]]


## ____Base Code:____
the general outline of how this works:
1. class created gives random number 2d array for every pixel
2. step does something (???)
3. 

In [5]:
# COLORSWIRL PART 1: IMPORTS-GLOBALS AND CLASS
import pygame
import numpy

W, H = 3, 3
FPS = 1

FLAGS = 0 #  | pygame.SCALED

class State:
    def __init__(self):
        # Create 2d NP array, and fill with random numbers between 0 and hex max for colors
        # these are the pixel's colors
        self.grid = numpy.random.randint(0, 0xFFFFFF + 1, (W, H), numpy.int32)

    def step(self):
        shifted = []
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                if (dx, dy) != (0, 0): 
                    # For each of direction ((-1,1)x*(-1,1)y), appends the entire random grid, shifted in that direction.
                    shifted.append(numpy.roll(self.grid, (dx, dy), (0, 1)))
        
        # For each pixel pick a random number, corresponding to each rolled array in shifted[]
        rand_vals = numpy.random.randint(0, len(shifted), (W, H), numpy.int16)

        masks = []
        for i in range(len(shifted)):
            masks.append(1 * (rand_vals == i))
        self.masks = masks
        self.grid[:] = 0
        for i in range(len(shifted)):
            self.grid += masks[i] * shifted[i]

    def draw(self, screen):
        pygame.surfarray.blit_array(screen, self.grid)

In [6]:
test = State()
test.step()
print(test.masks)

[array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]]), array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]]), array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]]), array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0]])]


In [ ]:
# COLORSWIRL PART 2: MAIN

if __name__ == "__main__":
    pygame.init()
    screen = pygame.display.set_mode((W, H), flags=FLAGS)
    state = State()
    clock = pygame.time.Clock()

    running = True
    last_update_time = pygame.time.get_ticks()

    while running:
        current_time = pygame.time.get_ticks()
        dt = (current_time - last_update_time) / 1000
        for e in pygame.event.get():
            if e.type == pygame.QUIT or (e.type == pygame.KEYDOWN and e.key == pygame.K_ESCAPE):
                running = False
            elif e.type == pygame.KEYDOWN:
                if e.key == pygame.K_r:
                    print("Resetting.")
                    state = State()
                elif e.key == pygame.K_RIGHT:
                    FPS += 10
                    print("Increased target FPS to: {}".format(FPS))
                elif e.key == pygame.K_LEFT:
                    FPS = max(10, FPS - 10)
                    print("Decreased target FPS to: {}".format(FPS))
        state.step()
        state.draw(screen)

        pygame.display.flip()

        if current_time // 1000 > last_update_time // 1000:
            pygame.display.set_caption("Color Swirl (FPS={:.1f}, TARGET_FPS={}, SIZE={})".format(clock.get_fps(), FPS, (W, H)))

        last_update_time = current_time
        clock.tick(FPS)


In [22]:
# How does Numpy.Roll work?
# shifted.append(numpy.roll(self.grid, (dx, dy), (0, 1)))
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.roll(a,(1,0),(0,0)))
print(np.roll(a,(0,1)))
print(np.roll(a,(0,1),(0,1)))
print(np.roll(a,(1,0),(0,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]
[[9 1 2]
 [3 4 5]
 [6 7 8]]
[[3 1 2]
 [6 4 5]
 [9 7 8]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]
