In [1]:
x = 20

print(20 // 7) # Floor division - returns highest integer that can fit (ie roudns down)

2


In [14]:
# Using Slicing (ie [:] for numpy arrays)
import numpy as np
import copy
list1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(list1)
# overwrite all values with 0 (only works with numpy array, not lists)
copy1 = copy.copy(list1)
copy1[:] = 0
# copy specific values of one array to another
val = 5
copy1[np.where(list1 == val)] = val
list1 = np.random.randint(9,size=(3,3))
print(list1)
print(copy1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 3 5]
 [1 4 3]
 [1 0 1]]
[[0 0 0]
 [0 5 0]
 [0 0 0]]


In [ ]:
# Make mask
import os
list1 = np.where()

